export default [
  { value: "ar", key: "ar", text: "Argentina" },
  { value: "at", key: "at", text: "Austria" },
  { value: "au", key: "au", text: "Australia" },
  { value: "be", key: "be", text: "Belgium" },
  { value: "bg", key: "bg", text: "Bulgaria" },
  { value: "br", key: "br", text: "Brazil" },
  { value: "ca", key: "ca", text: "Canada" },
  { value: "cn", key: "cn", text: "China" },
  { value: "co", key: "co", text: "Colombia" },
  { value: "cu", key: "cu", text: "Cuba" },
  { value: "cz", key: "cz", text: "Czech Republic" },
  { value: "eg", key: "eg", text: "Egypt" },
  { value: "fr", key: "fr", text: "France" },
  { value: "de", key: "de", text: "Germany" },
  { value: "gr", key: "gr", text: "Greece" },
  { value: "hk", key: "hk", text: "Hong Kong" },
  { value: "hu", key: "hu", text: "Hungary" },
  { value: "in", key: "in", text: "India" },
  { value: "id", key: "id", text: "Indonesia" },
  { value: "ie", key: "ie", text: "Ireland" },
  { value: "il", key: "il", text: "Israel" },
  { value: "it", key: "it", text: "Italy" },
  { value: "jp", key: "jp", text: "Japan" },
  { value: "lv", key: "lv", text: "Latvia" },
  { value: "lt", key: "lt", text: "Lithuania" },
  { value: "my", key: "my", text: "Malaysia" },
  { value: "mx", key: "mx", text: "Mexico" },
  { value: "ma", key: "ma", text: "Morocco" },
  { value: "ng", key: "ng", text: "Nigeria" },
  { value: "nl", key: "nl", text: "Netherlands" },
  { value: "nz", key: "nz", text: "New Zealand" },
  { value: "no", key: "no", text: "Norway" },
  { value: "ph", key: "ph", text: "Philippines" },
  { value: "pl", key: "pl", text: "Poland" },
  { value: "pt", key: "pt", text: "Portugal" },
  { value: "ro", key: "ro", text: "Romania" },
  { value: "ru", key: "ru", text: "Russia" },
  { value: "sa", key: "sa", text: "Saudi Arabia" },
  { value: "rs", key: "rs", text: "Serbia" },
  { value: "sg", key: "sg", text: "Singapore" },
  { value: "sk", key: "sk", text: "Slovakia" },
  { value: "si", key: "si", text: "Slovenia" },
  { value: "za", key: "za", text: "South Africa" },
  { value: "kr", key: "kr", text: "South Korea" },
  { value: "ch", key: "ch", text: "Switzerland" },
  { value: "se", key: "se", text: "Sweden" },
  { value: "tw", key: "tw", text: "Taiwan" },
  { value: "th", key: "th", text: "Thailand" },
  { value: "tr", key: "tr", text: "Turkey" },
  { value: "ua", key: "ua", text: "Ukraine" },
  { value: "ae", key: "ae", text: "United Arab Emirates" },
  { value: "gb", key: "gb", text: "United Kingdom" },
  { value: "us", key: "us", text: "United States" },
  { value: "ve", key: "ve", text: "Venezuela" },
];
